/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AnalyzeQueryIdImport } from './routes/analyze/$queryId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AnalyzeQueryIdRoute = AnalyzeQueryIdImport.update({
  path: '/analyze/$queryId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/analyze/$queryId': {
      id: '/analyze/$queryId'
      path: '/analyze/$queryId'
      fullPath: '/analyze/$queryId'
      preLoaderRoute: typeof AnalyzeQueryIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze/$queryId': typeof AnalyzeQueryIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze/$queryId': typeof AnalyzeQueryIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/analyze/$queryId': typeof AnalyzeQueryIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyze/$queryId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyze/$queryId'
  id: '__root__' | '/' | '/analyze/$queryId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeQueryIdRoute: typeof AnalyzeQueryIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeQueryIdRoute: AnalyzeQueryIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/analyze/$queryId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/analyze/$queryId": {
      "filePath": "analyze/$queryId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
